### ISSUE TITLE
SliceViewer is killed when a SliceProvider is uninstalled/updated

### ISSUE THREAD

**Issue by defer** [googlesamples/android-SliceViewer#1]
Steps to reproduce:
1) Install SliceViewer
2) Install a slice provider (separate app)
3) Add the slice URI, grant permissions, etc
4) Uninstall or update the provider apk
5) SliceViewer crashes

Digging a bit through the issue, it looks like SliveLiveData keeps a connection to the content provider via SliceManager. On the platform side, when the content provider is removed, all its active clients are killed:

05-16 14:42:06.660  1787  1801 I ActivityManager: Killing 21336:com.example.android.sliceviewer/u0a100 (adj 0): depends on provider com.example.slices.provider/.DemoSliceProvider in dying proc com.example.slices.provider (adj 0)

Given that this might be a more fundamental platform issue, please let me know if this is not the appropriate reporting medium.

**Comment by DougSig** [comment]
Thanks for reporting. This is being fixed internally. I will close the bug when a public release of slices has the fix.
